export default{
    //是否正在播放
    isPlaying:false,
    //是否显示播放界面
    showPlayer:false,
    //当前播放列表
    currentPlayList:[],
    //上一首的索引
    preIndex:'',
    //当前歌曲索引
    //自动停止，即当前歌曲播放完毕，非人为停止，
    naturalPause:true,
    index:-1,
    //当前播放的音乐信息
    currentMusic:{
        id:'',
        name:'',
        singer:'',
        src:'',
        lyric:'',
        bg:'',
        duration:'00:00',
        totalComment:'',
        //热门评论
        hotComments:[],
        //普通评论
        normalComments:[]
    },
    //当前用户
    currentUser:{
        id:'132444139',
        //用户创建的歌单
        createdList:[],
        //用户收藏的歌单
        collectedList:[],
        //用户喜欢的歌列表
        likeArr:null
    }
}